"""initial

Revision ID: 8a5145c40a8a
Revises: 
Create Date: 2026-05-12 18:25:15.015700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8a5145c40a8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reswords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('type_fk', sa.Integer(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('release_ts', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['type_fk'], ['settype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_fk', sa.Integer(), nullable=False),
    sa.Column('cardtype_fk', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('life', sa.Integer(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cardtype_fk'], ['cardtype.id'], ),
    sa.ForeignKeyConstraint(['set_fk'], ['set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardattribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('attribute_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_fk'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('block_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_fk'], ['block.id'], ),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardcolor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('color_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.ForeignKeyConstraint(['color_fk'], ['color.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardformat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('format_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.ForeignKeyConstraint(['format_fk'], ['format.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardkeywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('keywords_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.ForeignKeyConstraint(['keywords_fk'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardrarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('rarity_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.ForeignKeyConstraint(['rarity_fk'], ['rarity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardreswords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('reswords_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.ForeignKeyConstraint(['reswords_fk'], ['reswords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardtribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('tribe_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.ForeignKeyConstraint(['tribe_fk'], ['tribe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('naip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Date(), nullable=True),
    sa.Column('updated_ts', sa.Date(), nullable=True),
    sa.Column('card_fk', sa.Integer(), nullable=False),
    sa.Column('set_fk', sa.Integer(), nullable=False),
    sa.Column('artist_fk', sa.Integer(), nullable=True),
    sa.Column('rarity_fk', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['artist_fk'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['card_fk'], ['card.id'], ),
    sa.ForeignKeyConstraint(['rarity_fk'], ['rarity.id'], ),
    sa.ForeignKeyConstraint(['set_fk'], ['set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('naip')
    op.drop_table('cardtribe')
    op.drop_table('cardreswords')
    op.drop_table('cardrarity')
    op.drop_table('cardkeywords')
    op.drop_table('cardformat')
    op.drop_table('cardcolor')
    op.drop_table('cardblock')
    op.drop_table('cardattribute')
    op.drop_table('card')
    op.drop_table('set')
    op.drop_table('tribe')
    op.drop_table('settype')
    op.drop_table('reswords')
    op.drop_table('rarity')
    op.drop_table('keywords')
    op.drop_table('format')
    op.drop_table('color')
    op.drop_table('cardtype')
    op.drop_table('block')
    op.drop_table('attribute')
    op.drop_table('artist')
    # ### end Alembic commands ###
